  CREATE TABLE AUTOR (
  ID SERIAL NOT NULL,
  VORNAME varchar(255),
  NACHNAME varchar(255),
  GEB_DATUM date,
  EINZELBUERO_ID int4,
  VERLAG_ID int4 ,
  PRIMARY KEY (ID));


CREATE TABLE VERLAG (
  ID SERIAL NOT NULL,
  NAME varchar(255),
  STRASSE varchar(255),
  ORT varchar(255),
  PLZ int4,
  PRIMARY KEY (ID));

CREATE TABLE EINZELBUERO (
  ID SERIAL NOT NULL,
  STRASSE varchar(255),
  ORT varchar(255),
  PLZ int4,
  PRIMARY KEY (ID));

CREATE TABLE BUCH (
  ID SERIAL NOT NULL,
  ISBN int4,
  TITEL varchar(255),
  ERSCHEINUNGSJAHR date,
  GENRE_ID int4,
  PRIMARY KEY (ID));


CREATE TABLE AUTOR_BUCH (
  BUECHER_ID SERIAL NOT NULL,
  AUTOREN_ID SERIAL NOT NULL,
  PRIMARY KEY (BUECHER_ID, AUTOREN_ID),
  CONSTRAINT FK_BUCH_AUTOR FOREIGN KEY (BUECHER_ID)
  REFERENCES BUCH (ID),
  CONSTRAINT FK_AUTOR_BUCH FOREIGN KEY (AUTOREN_ID)
  REFERENCES AUTOR (ID)
);

CREATE TABLE GENRE (
  ID SERIAL NOT NULL,
  GENRE varchar(255),
  PRIMARY KEY (ID));

ALTER TABLE AUTOR
  ADD CONSTRAINT FK_AUTOR_EINZELBUERO FOREIGN KEY (EINZELBUERO_ID)
REFERENCES EINZELBUERO (ID);

ALTER TABLE AUTOR ADD CONSTRAINT FK_AUTOR_VERLAG FOREIGN KEY (VERLAG_ID)
REFERENCES VERLAG (ID);

ALTER TABLE BUCH ADD CONSTRAINT FK_BUCH_GENRE FOREIGN KEY (GENRE_ID)
REFERENCES GENRE (ID);