  CREATE TABLE AUTOR (
  ID INT NOT NULL,
  VORNAME varchar(255),
  NACHNAME varchar(255),
  GEB_DATUM date,
  EINZELBUERO_ID int4,
  VERLAG_ID int4 ,
  PRIMARY KEY (ID));


CREATE TABLE VERLAG (
  ID INT NOT NULL,
  NAME varchar(255),
  STRASSE varchar(255),
  ORT varchar(255),
  PLZ int4,
  PRIMARY KEY (ID));

CREATE TABLE EINZELBUERO (
  ID INT NOT NULL,
  STRASSE varchar(255),
  ORT varchar(255),
  PLZ int4,
  PRIMARY KEY (ID));

CREATE TABLE BUCH_AUTOR (
  ID INT NOT NULL,
  BUCH_ID int4 NOT NULL,
  AUTOR_ID int4 NOT NULL);


CREATE TABLE BUCH (
  ID INT NOT NULL,
  ISBN int4,
  TITEL varchar(255),
  ERSCHEINUNGSJAHR date,
  GENRE_ID int4,
  PRIMARY KEY (ID));

CREATE TABLE GENRE (
  ID INT NOT NULL,
  GENRE varchar(255),
  PRIMARY KEY (ID));

ALTER TABLE AUTOR
  ADD CONSTRAINT FK_AUTOR_EINZELBUERO FOREIGN KEY (EINZELBUERO_ID)
REFERENCES EINZELBUERO (ID);

ALTER TABLE AUTOR ADD CONSTRAINT FK_AUTOR_VERLAG FOREIGN KEY (VERLAG_ID)
REFERENCES VERLAG (ID);

ALTER TABLE BUCH ADD CONSTRAINT FK_BUCH_GENRE FOREIGN KEY (GENRE_ID)
REFERENCES GENRE (ID);